### ISSUE TITLE
Preparação

### ISSUE THREAD

**Issue by bernas1104** [bernas1104/appDev#1]
# Instalação do Ambiente

- Para iniciar os trabalhos da disciplina, os membros da equipe (@bernas1104, @JomaSnow e @PedrosUsername) precisam instalar o ambiente de desenvolvimento do Flutter.

## Flutter

- Para instalação dos arquivos do Flutter é necessário acessar o site: https://flutter.dev/docs/get-started/install e seguite os passos descritos. O processo é bastante simples e não deve gerar grandes problemas.

## IDE

- Para o desenvolvimento simplificado - integrado com o Flutter - existem algumas opções. Entre elas podemos citar o IntelliJ Community, VS Code e Android Studio. Eles podem ser baixados nos links abaixo:
- https://www.jetbrains.com/idea/download/
- https://code.visualstudio.com/download
- https://developer.android.com/studio/index.html?hl=es-419#downloads

## Display-Mirroring

- Para facilitar o desenvolvimento, os membros da equipe devem fazer o download do Vysor. A instalação - principalmente no Linux - é bastante simples e seu uso é resumido em um clique. Pode ser baixado no link https://www.vysor.io/download/.

**Comment by JomaSnow** [comment]
Todos os membros já possuem um ambiente funcional.
